ro.boot.flash.locked=1

# Bootloader锁定状态属性。
#
# 解锁设备通常：
# ro.boot.flash.locked=0
#
# 修改后：
# Android userspace读取结果显示Bootloader已锁定。


ro.boot.verifiedbootstate=green

# Verified Boot验证状态。
#
# orange:
# Bootloader解锁状态。
#
# green:
# 验证通过状态。


ro.build.type=user

# Android Build类型。
#
# user:
# 正式版本。
#
# userdebug:
# 调试版本。


ro.build.tags=release-keys

# Build签名标签。
#
# test-keys:
# 测试编译。
#
# release-keys:
# 正式发布签名。
