#################################################
# BL Lock Environment Configuration
#################################################


#################################################
# 1. Bootloader / AVB Environment
#################################################

ro.boot.flash.locked=1
#策略：VERIFY
# Bootloader锁定状态属性。
#
# 解锁设备通常：
# ro.boot.flash.locked=0
#
# 修改后：
# Android userspace读取结果显示Bootloader已锁定。


ro.boot.vbmeta.device_state=locked
#策略：VERIFY
# AVB vbmeta设备状态。
#
# unlocked：
# Bootloader解锁状态。
#
# locked：
# 模拟锁定状态。


vendor.boot.vbmeta.device_state=locked
#策略：VERIFY
# Vendor侧VBMeta设备状态。
#
# 部分厂商Framework读取vendor属性。


ro.boot.verifiedbootstate=green
#策略：VERIFY
# Verified Boot验证状态。
#
# orange：
# Bootloader解锁。
#
# green：
# 验证通过。


vendor.boot.verifiedbootstate=green
#策略：VERIFY
# Vendor侧Verified Boot状态。


ro.boot.veritymode=enforcing
#策略：VERIFY
# dm-verity运行模式。
#
# enforcing：
# 强制验证模式。


#################################################
# 2. Build Identity
#################################################

ro.build.type=user
#策略：VERIFY
# Android Build类型。
#
# user：
# 正式版本。
#
# userdebug：
# 调试版本。


ro.build.tags=release-keys
#策略：VERIFY
# Android Build签名标签。
#
# test-keys：
# 测试编译。
#
# release-keys：
# 正式发布。


#################################################
# 3. Security Environment
#################################################

ro.debuggable=0
#策略：VERIFY
# Android Debug状态属性。
#
# 1：
# 调试版本环境。
#
# 0：
# 正式版本环境。


ro.force.debuggable=0
#策略：VERIFY
# 强制Debug状态控制。


ro.secure=1
#策略：VERIFY
# Android安全模式属性。
#
# 正式用户系统通常为1。


ro.adb.secure=1
#策略：VERIFY
# ADB安全认证状态。


#################################################
# 4. OEM Unlock State
#################################################

sys.oem_unlock_allowed=0
#策略：VERIFY
# OEM Unlock允许状态。


#################################################
# 5. Warranty / Tamper State
#################################################

ro.boot.warranty_bit=0
#策略：VERIFY
# Boot阶段Warranty状态。


ro.warranty_bit=0
#策略：VERIFY
# Android Warranty状态。


ro.vendor.boot.warranty_bit=0
#策略：VERIFY
# Vendor Boot Warranty状态。


ro.vendor.warranty_bit=0
#策略：VERIFY
# Vendor Warranty状态。


#################################################
# 6. OEM Specific
#################################################

ro.secureboot.lockstate=locked
#策略：VERIFY
# Xiaomi Secure Boot状态。


ro.boot.realmebootstate=green
#策略：VERIFY
# Realme Boot状态。


ro.boot.realme.lockstate=1
#策略：VERIFY
# Realme Bootloader状态。
